name: Feature Branch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Run unit tests
        run: bash ./gradlew test --stacktrace

    instrumented-test:
      name: Instrumented Tests
      runs-on: macos-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Run instrumented tests
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: 29
            script: ./gradlew connectedCheck

    build-apk:
      name: Generate APK
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Set up JDK 1.8
          uses: actions/setup-java@v1.4.3
          with:
            java-version: 1.8

        - name: Build debug APK
          run: bash ./gradlew assembleDebug --stacktrace

        - name: Upload debug APK
          uses: actions/checkout@v2
          path: app/build/outputs/apk/debug/app-debug.apk
